### PR TITLE
Added subtype to custom field. Used ResourceWithSubtype instead of se…

### PR DESCRIPTION
**Pull request by rossgrambo**
…lf declared subtypes

### CODE REVIEW

**Comment by rossgrambo** [comment]
See https://github.com/Asana/java-asana/issues/92

**Comment by AntonyLeons** [comment]
@rossgrambo This causes errors.
`Cannot find symbol variable resource subtype`
Intelij recognises the object but java fails to compile
This is why I closed my pull request more work needs to be done for this to work properly.

**Comment by rossgrambo** [comment]
@AntonyLeons , Could you supply your line that can't be compiled? Also your version of java?

I'm not having any issues.
```
        CustomField customField = new CustomField();
        customField.resourceSubtype = "This is a subtype";
        System.out.println("Resource Subtype: " + customField.resourceSubtype);
```

**Comment by AntonyLeons** [comment]
@rossgrambo  sorry But the issue has resolved itself, probably just cache issues with intellij. thanks for the help

**Pull request merged**
